apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: staging
namePrefix: stg-
images:
- name: nginx
  newTag: 1.27.1
configMapGenerator:
- name: nginx-configmap
  files:
    - index.html
