apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: staging
namePrefix: stg-

#Nginx Image Version
images:
- name: nginx
  newTag: 1.27.1

#ConfigMap
configMapGenerator:
- name: nginx-configmap
  files:
    - index.html

patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: nginx-web
      namespace: staging
    path: ./replicas.yaml
