apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: production
namePrefix: prd-
images:
- name: nginx
  newTag: 1.26.2
configMapGenerator:
- name: nginx-configmap
  files:
    - index.html
