apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-env
patches:
- path: patch.yaml
  target:
    kind: Deployment
    name: nginx-web
resources:
- ../../base
commonLabels:
  env: dev
