apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-env
namePrefix: test-
resources:
- ../../base/
configMapGenerator:
- name: nginx-configmap
  behavior: replace
  files:
    - index.html

