---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-web
  name: nginx-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-web
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-configmap
      volumes:
        #- name: nginx-configmap
        configMap:
          #name: nginx-configmap  
